### PR TITLE
fix #400, improve browser linter

### LINKED ISSUE #400: improve browser linter
I suggest the regex used in `hasBrowserCalls` can be a little too permissive:

https://github.com/rstudio/rsconnect/blob/0aafa8855bdd04db4640fd091575778146992b00/R/lint-utils.R#L6-L10

In an internal project, it falsely matched a function I wrote (`fake_browser`) that is not an interactive-only thing. I suggest the regex be tightened, perhaps just a word boundary: `"\\bbrowser\\([^)]*\\)"`.

Do you think this would be too-restrictive as a general case?

(In case it helps: win10, R-3.5.3, rsconnect-0.8.16, deploying to RSC-1.8.0

### PR DESCRIPTION
**Pull request by r2evans**
implemented fix for #400

### CODE REVIEW

**Comment by r2evans** [comment]
@kevinushey 

Do you want/need an entry in `NEWS.md` as well?

**Comment by r2evans** [comment]
(I hope you don't mind that I inferred a similar fix for `browseURL` would be warranted. Easily removed if you prefer.)

**Comment by kevinushey** [comment]
A news entry would be appreciated. Thanks!

**Comment by jmcphers** [comment]
@r2evans Very much appreciate the contribution!

**Pull request merged**
