### PR TITLE
add missing 'service' parameters

### PR DESCRIPTION
**Pull request by kevinushey**
Should resolve https://github.com/rstudio/rsconnect/issues/137.

### CODE REVIEW

**Comment by kevinushey** [comment]
Although the request is made successfully, the server doesn't seem to like it:

```
> rsconnect::setProperty('application.visibility', 'private', account = 'lodashkev', appName = 'rplot')
Error: HTTP 400
PUT https://beta.rstudioconnect.com/__api__/applications/2048/properties/application.visibility?force=0
The requested endpoint or method is invalid. 
```

Note that this code path uses the `lucid` client; perhaps we also need to be detecting + using the `connect` client instead?

**Comment by jspiewak** [comment]
#137 was against shinyapps.io, so `lucid` is correct.
I am not sure whether or not connect supports this.

**Comment by kevinushey** [comment]
Got it -- then it should definitely work in that case. Thanks!

**Comment by jspiewak** [comment]
poke?

**Comment by kevinushey** [comment]
@jjallaire can you sanity check and merge if all looks fine?

**Pull request merged**
