### PR TITLE
Align with CRAN policy for configuration storage

### PR DESCRIPTION
**Pull request by jmcphers**
This change aligns us with the new CRAN policy for configuration storage. Configuration is now stored in the directory named by `tools::R_user_dir()`.

Notes:
- Migration from old directories, of which we now have two, is implemented. This mostly just follows the existing path for migration from the boring old single deprecated folder we had prior to this change.
- The `R_user_dir` function is new in R 4.0.0. We use it when it's available; when it isn't, we have a fallback that uses identical code to compute the configuration folder.
- This will, very unfortunately, require a change in the IDE, because the IDE has some logic to detected orphaned rsconnect accounts (in which the account exists but the rsconnect package is not installed). We will make that once this is merged, and acknowledge that there will now be some combinations of IDE versions and rsconnect package versions for which we cannot detect orphaned accounts.

Fixes https://github.com/rstudio/rsconnect/issues/550

### CODE REVIEW

**Review by aronatkins — APPROVED** [review]

**Comment by kevinushey** [comment]
> This will, very unfortunately, require a change in the IDE, because the IDE has some logic to detected orphaned rsconnect accounts (in which the account exists but the rsconnect package is not installed). We will make that once this is merged, and acknowledge that there will now be some combinations of IDE versions and rsconnect package versions for which we cannot detect orphaned accounts.

Would things be made any simpler if rsconnect, rather than migrating these files, simply checked each of the locations in turn? Then, we could re-use an older existing configuration at its original location if it's already there, but prefer the new location for newly-created storage.

**Comment by jmcphers** [comment]
> Would things be made any simpler

I don't think so; in no circumstance can we avoid the IDE having to know about every possible configuration folder that rsconnect could be using.

**Comment by kevinushey** [comment]
My main worry is that if we migrate by default, then all existing versions of the IDE will be unable to detect orphaned accounts with this version of rsconnect. (Maybe that's ultimately not a huge deal.)

If we only migrate on demand, then the only breakages would be in users who are brand new to rsconnect, and have installed the latest version of rsconnect, but who haven't yet updated to the latest version of the IDE. In other words, existing users of the IDE / rsconnect shouldn't be affected.

FWIW, CRAN _technically_ allows you to write into arbitrary user locations as long as you obtain user consent:

> - Packages should not write in the user’s home filespace (including clipboards), nor anywhere else on the file system apart from the R session’s temporary directory (or during installation in the location pointed to by TMPDIR: and such usage should be cleaned up). Installing into the system’s R installation (e.g., scripts to its bin directory) is not allowed.
> **Limited exceptions may be allowed in interactive sessions if the package obtains confirmation from the user.**

so we could also request permission from the user in some context before writing / using the current `rappdirs`-generated storage location, and just use some other CRAN-permissible fallback if we detect that we're running our tests on CRAN.

**Comment by aronatkins** [comment]
@kevinushey @jmcphers - have you reached consensus?

I'm assuming that new versions of the IDE can force new versions of rsconnect, but I'd like to confirm that old versions of the IDE will cope with new versions of rsconnect. We very often ask folks to update rsconnect without requiring an IDE upgrade.

From a quick code-read, it appears as if `.rs.connectConfigDir` is only used for orphaned accounts, as @jmcphers indicated, and everything else is backed by the `rsconnect` package. That feels like low-risk, as it means we'll miss suggesting an rsconnect install in one path, only to trigger that install elsewhere.

**Comment by kevinushey** [comment]
> From a quick code-read, it appears as if .rs.connectConfigDir is only used for orphaned accounts, as @jmcphers indicated, and everything else is backed by the rsconnect package. That feels like low-risk, as it means we'll miss suggesting an rsconnect install in one path, only to trigger that install elsewhere.

If that's the case, then I think we're probably fine to just take this PR as-is. I was mainly worried about a case where updating `rsconnect` could mean people with older versions of the IDE were suddenly unable to deploy, or manage deployments, or similar.

**Comment by aronatkins** [comment]
It sounds like the remaining risk is that folks cannot easily revert to older versions of rsconnect after updating; they would need to move the stored data back to the old location or reconfigure. This will mostly impact us, when testing different versions, but is probably meaningful enough that we should add a NEWS entry.

I'll add NEWS to this branch ahead of merge.

**Comment by hadley** [comment]
I'm not 100% sure this is the correct fix. There are two considerations:

1. Where should a package store data/config/cache files?
2. Is it ok to store files in these directories during check?

I _think_ the problem that this check NOTE is trying to catch is 2, not 1. This is based on my reading of [the check source](https://github.com/wch/r-source/blob/76c2ecd2e40c9dd9e8bde7b3862783c914ef4ab7/src/library/tools/R/check.R#L451-L476); this scan is trigged by `_R_CHECK_THINGS_IN_OTHER_DIRS_=true` which I think is the NOTE that's affecting us all. 

I'm attempting to replicate BDR's [donttest](https://www.stats.ox.ac.uk/pub/bdr/donttest/README.txt) check results at https://github.com/rstudio/pins/pull/562, without success so far.

**Comment by aronatkins** [comment]
The check cleanup happened previously, in https://github.com/rstudio/rsconnect/commit/aca4c18fb39f0581ad52e234c618e3c9f1192c82 and https://github.com/rstudio/rsconnect/commit/8088f0f40ec2cd19cf92bfd7fc2d735c29a7c53f and https://github.com/rstudio/rsconnect/commit/8e1fbebc19f88a6ba69de287d450ae7edb8bb57f.

**Pull request merged**
