### PR TITLE
Add new default 'libcurl' transport

### PR DESCRIPTION
**Pull request by jmcphers**
This change adds a new HTTP transport, "libcurl", and makes it the default. This new transport uses the curl package, which is significantly more modern and better maintained than RCurl. Consequently we're also able to restore a unified HTTP transport default across all operating systems (we formerly had to use the command-line "curl" transport on Windows due to issues with the aging RCurl). 

The diff is noisier than it needs to be since it includes some file splitting; `http.R` had grown to over 1200 lines. Each transport now has its own file. 

The other source of noise is a complete re-write of how we handle streaming logs from shinyapps.io, necessitated because curl and RCurl handle streaming differently. Thankfully the new implementation is much more succinct and doesn't require a child R process. 

Closes https://github.com/rstudio/rsconnect/issues/325.

### CODE REVIEW

**Comment by jeroen** [comment]
Looks great! One note: I see you are manually parsing cookies from the header, are you aware libcurl has a native function for this called `handle_cookies()`? See https://cran.r-project.org/web/packages/curl/vignettes/intro.html#reading_cookies

**Comment by jmcphers** [comment]
Yes, I saw that! Very useful. However we have our own internal cookie implementation that we use on all the other transports, and re-using it was more straightforward than adding additional state management to keep curl handles around.

**Comment by jeroen** [comment]
You could also consider dropping `RCurl` as hard dependency by moving it into `Suggests`. Because besides not working well, it's also a pain to install on some systems. On Windows it requires a special system setup to install from source.

**Comment by jmcphers** [comment]
@jeroen That's a good idea; done: https://github.com/rstudio/rsconnect/commit/35ba0497f7266da2c9157cbcd1b55e29c2876b4d

**Pull request merged**
