### PR TITLE
Emit additional dependencies for Packrat based on app mode (fixes #21)

### LINKED ISSUE #21: deployApp should inject shiny dependency
server.R
```
shinyServer(function(input, output) {})
```
ui.R
```
shinyUI(fluidPage(
  titlePanel("Hello Shiny!")
))
```

I can run the application in the IDE. I can deploy the application both with the IDE and manually via `rsconnect::deployApp`. In both bundles, we do not identify `shiny` as a dependency because it does not explicitly appear in a `library` statement.

The app will fail to start if the deployment target does not have shiny installed. If shiny is installed on the target, it may be the incorrect version.

Workaround is to use a `library(shiny)` statement.

### PR DESCRIPTION
**Pull request by jmcphers**
This change causes RSConnect to write a temporary .R file prior to snapshotting a project's dependencies with Packrat. 

The .R file includes `library` statements that make explicit dependencies from dependencies that might formerly have been implicit (such as Shiny or R Markdown).

### CODE REVIEW

**Comment by kevinushey** [comment]
Looks good to me.

**Comment by jjallaire** [comment]
Does this just apply to Rmd or does it emit shiny for regular Shiny apps?

**Comment by jmcphers** [comment]
It emits shiny for regular Shiny apps too (`\bshiny\b` matches app modes `shiny` and `rmd-shiny`).

**Comment by aronatkins** [comment]
Do we have tests showing that rsconnect produces the expected bundles for different types of apps?

**Pull request merged**
