### PR TITLE
Added note that terminating also archives the application

### PR DESCRIPTION
**Pull request by martinjhnhadley**
It isn’t clear from the documentation that termination is analogous
with archiving.

### CODE REVIEW

**Comment by jjallaire** [comment]
@trestletech Does terminateApp work on RSConnect or just shinyapps.io? If it does, does the archiving behavior differ between platforms? Just want to make sure that the docs reflect accurately what happens in both environments.

**Comment by kippandrew** [comment]
Terminate and Archive are the same. FWIW, I would be in favor of deprecating the `terminateApp` function and renaming it to `archiveApp`. "Terminate" was never a good name to begin with, which is why it was changed in the web UI.

**Comment by kippandrew** [comment]
An update to my pervious comment: 'terminate' and 'archive' mean the same things in shinyapps.io, not sure about RSC.

**Comment by jjallaire** [comment]
Okay, so let's revise the PR to add a new function "archiveApp" and to have the old function alias the new one with a deprecation warning. Jeff, let us know about RSConnect.

**Comment by trestletech** [comment]
We don't use Terminate in RSC today.

**Comment by jjallaire** [comment]
Okay, @martinjhnhadley if you could modify the PR to also mention that this only works on shinyapps.io that would be great (we'll take care of the rename / deprecation).

**Comment by martinjhnhadley** [comment]
@jjallaire that's great - thanks for handling the deprecation!

**Pull request merged**
