### PR TITLE
Republishing to RPubs is broken from RStudio

### LINKED ISSUE #976: Republishing to RPubs, Error: HTTP/2 stream 1 was reset
AN ERROR OCCURS when I knit an Rmd into HTML and republish (update existing) it to RPubs. There is no problem with the initial upload or republishing long ago Rmd.

`Error in curl::curl_fetch_memory(url, handle = handle) :  HTTP/2 stream 1 was reset Calls: <Anonymous> -> http -> <Anonymous> Execution halted`

I have tried the simplest HTML document. So, the error is not due to the file size.

R version 4.3.1
RStudio version 2023.09.0+463 
macOS Ventura 13.5.2
MacBook Air, M2

I fixed the republishing issue by downgrading the "rsconnect" R package.

```
remove.packages("rsconnect") #Remove Installed Packages
remotes::install_version("rsconnect", version = "0.8.29") #Installing a Specific Version of a Package
```

Any higher versions of rsconnect (e.g., 1.0.0, 1.0.1, 1.0.2, 1.1.0 and latest 1.1.1) will cause the error regarding "HTTP/2 stream 1 was reset". After downgrading "rsconnect", RMD files with failed republishing will still not be republished. You need to upload a fresh one.

### PR DESCRIPTION
**Pull request by jcheng5**
Fixes #976. See https://github.com/rstudio/rsconnect/issues/976#issuecomment-1760090198 for explanation.

### CODE REVIEW

**Comment by aronatkins** [comment]
Thanks, @jcheng5! I'll take it from here, fix the lint complaints and add NEWS.

**Comment by aronatkins** [comment]
I've confirmed that rpubs republishing is fixed with this change.

Unfortunately, the off-by-one deployment record means that existing documents are "stuck".

Folks can either use `rsconnect::forgetDeployment()` or manually adjust the rsconnect deployment record.

Assuming I'm publishing from an `index.Rmd` file, the deployment record lives at:
`rsconnect/documents/index.Rmd/rpubs.com/rpubs/Document.dcf`

An example "bad" record:

```dcf
name: Document
title:
username:
account: rpubs
server: rpubs.com
envVars: rpubs.com
hostUrl: https://api.rpubs.com/api/v1/document/1097969/984f9439141d43f4a35ae663a972522e
appId: https://api.rpubs.com/api/v1/document/1097969/984f9439141d43f4a35ae663a972522e
bundleId: http://rpubs.com/publish/claim/1097969/4ef82fe6cb3f41f39e42de23caf3e806
url: 1697138036.07503
version: 1
```

An example "good" record:

```dcf
name: Document
title:
username:
account: rpubs
server: rpubs.com
hostUrl: rpubs.com
appId: https://api.rpubs.com/api/v1/document/1097975/bf849d4b51884d1a9716e7028e5b33a6
bundleId: https://api.rpubs.com/api/v1/document/1097975/bf849d4b51884d1a9716e7028e5b33a6
url: http://rpubs.com/publish/claim/1097975/e57795f1581b4f30a16c353b4ae7c911
version: 1
```

There were two mistakes:

1. an `envVars` argument was not added
2. the `when` and `lastSyncTime` arguments were removed.

**Review by aronatkins — APPROVED** [review]

**Comment by jcheng5** [comment]
Thanks @aronatkins!

**Comment by JBell39** [comment]
I don't know what I am doing wrong. Here is my updated dcf:

< 
name: Document
title:
username:
account: rpubs
server: rpubs.com
hostUrl: rpubs.com
appId: https://api.rpubs.com/api/v1/document/1099849/f24f13c92bd4430a8e6d83d25154f1fc
bundleId: http://rpubs.com/publish/claim/1099849/37d672b76e4748539e6d5983395371e5
url:  https://rpubs.com/bellj39/1099849
version: 1
>

**Comment by JBell39** [comment]
> I don't know what I am doing wrong. Here is my updated dcf:
> 
> ```
> name: Document
> title:
> username:
> account: rpubs
> server: rpubs.com
> hostUrl: rpubs.com
> appId: https://api.rpubs.com/api/v1/document/1099849/f24f13c92bd4430a8e6d83d25154f1fc
> bundleId: http://rpubs.com/publish/claim/1099849/37d672b76e4748539e6d5983395371e5
> url:  https://rpubs.com/bellj39/1099849
> version: 1
> ```

NM! I friggin' figured it out. lol. Thank you!

**Pull request merged**
