### PR TITLE
rely on README.md, not Rmd

### PR DESCRIPTION
**Pull request by aronatkins**
Any reason to preserve the R Markdown -> GitHub Markdown conversion?

### CODE REVIEW

**Comment by hadley** [comment]
Probably not that important now, but it does make it easy to add actual running examples. But maybe that's not terribly feasiable for rsconnect. I don't have strong feelings either way.

**Comment by aronatkins** [comment]
The Markdown and R Markdown versions have occasionally fallen out-of-sync, thus this PR. I'm open to other approaches which keep the README in sync.

**Comment by hadley** [comment]
I guess I don't worry too much about the `README.md` getting out of sync because I know one of the items on the release checklist is to run `devtools::build_readme()`, so there is a guaranteed sync point prior to release.

**Comment by aronatkins** [comment]
We have been following https://github.com/rstudio/rsconnect/blob/main/RELEASE.md, which doesn't include that step (unfortunately). It should.

**Comment by hadley** [comment]
Ah we should switch much of that to `usethis::use_release_issue()`

**Comment by aronatkins** [comment]
Updating our release checklist to `devtools::build_readme()` rather than shifting to the Markdown version.

**Pull request closed without merging**
