### PR TITLE
handle unknown and Local package source

### LINKED ISSUE #1004: Changes in renv/rsconnect - now getting "Local" packages in our CI/CD pipeline
Not entirely sure this is an issue - but this seems like the best place to get advice/answers - so please forgive me asking here.

For many of our apps, reports and apis, our repos and CI/CD pipelines work by:

- each repo contains a package and one or more apps
- the package is version 9.9.9 in dev/git 
- the build pipeline:
  - stamps an incrementing version number on top
  - uses devtools to build the package (just a zip)
  - uses devtools to install the local package from disk
  - uploads the package to either our test CRAN or to our real CRAN
  - runs rsconnect writeManifest and deploy steps to deploy to either our test Connect or to our prod Connect
 
This pipeline's been working pretty well for a couple of years and is very stable.

Right now I'm looking at a breaking change in our pipelines following upgrading rsconnect to 1.x. What I'm seeing is that the currently built package is being picked up in the auto-generated manifest.json as: 
```
    "R.Brandy": {
      "Source": "Local",
      "Repository": "OurCo.IMS",
      "description": {
        "Package": "R.Brandy",
        "Type": "Package",
        "Title": "Shiny support for OurCo look and feel including the Unified\nDesign System",
        "Authors@R": "...",
        "Description": "R package with functions exposing Shiny Unified Design.",
        "Version": "0.1.209",
        "Maintainer": "...",
        "License": "file LICENSE",
        "Encoding": "UTF-8",
        "Repository": "OurCo.IMS",
        "Imports": "htmltools, shiny, dplyr, rmarkdown, purrr, magrittr,\ndownloadthis, rlang, jsonlite, stringr, rstudioapi, ggplot2,\nbase64enc, tibble, readr",
        "RoxygenNote": "7.2.1",
        "NeedsCompilation": "no",
        "Packaged": "2023-09-26 15:18:59 UTC; azdagent_azpcontainer",
        "Author": "Support [aut, cre]",
        "Built": "R 4.2.0; ; 2023-09-26 15:19:03 UTC; unix",
        "RemoteType": "local",
        "RemoteUrl": "/__w/1/a/package/R.Brandy_0.1.209.tar.gz"
      }
    },
```

The problem here are the line:
```
      "Source": "Local",      
      "Repository": "OurCo.IMS",
```

These cause the Connect deployment step to fail with lots of messages like...

```
2023/09/26 15:21:19.810629517 curl: (6) Could not resolve host: OurCo.IMS
2023/09/26 15:21:19.810642129 curl: HTTP 000 http://OurCo.IMS/src/contrib/Archive/R.Brandy/R.Brandy_0.1.210.tar.gz
```

Under previous versions of rsconnect (which I guess were less renv based) the manifest was written as:
```
    "R.Brandy": {
      "Source": "OurCo.IMS",
      "Repository": "https:/cran-uat.ourco.app/ims",
      "description": {
``` 
which just worked (TM)

I'm currently wondering if there's anything I can toggle inside rsconnect/renv to make it pick up that this package should be looked up in CRAN...

If not then I can change the build system it so that it installs from our CRAN server(s) before doing the deployment. I'm just hesitating before doing this second option, though, as there are subtleties there (and as I've broken production stability enough already this month!)

Just wondering if anyone has any other suggestions/ideas...

### PR DESCRIPTION
**Pull request by aronatkins**
This shifts from using a local "Source" with whatever "Repository" comes from renv to using NA for both. An error now occurs because the package did not come from a well-known repository.

fixes #1004

```r
# Create a new project and launch a separate RStudio session.
usethis::create_project("~/Desktop/mixed-content")

# In that new project ...
unlink("R", recursive = TRUE)
writeLines(c(
    "library(shiny)",
    "shinyApp('single file Shiny deploy', function(input, output) {})"
), "app.R")

renv::init()
renv::install(c("rsconnect"), prompt = FALSE)
renv::install("~/Downloads/shiny_1.7.5.tar.gz", repos = NULL, type = "source", prompt = FALSE)
renv::snapshot(prompt = FALSE)

rsconnect::writeManifest()
jsonlite::fromJSON("manifest.json")$packages$shiny[c("Source","Repository")]
#> $Source
#> [1] "Local"
#>
#> $Repository
#> [1] "CRAN"

renv::install("rstudio/rsconnect@aron-issue-1004", prompt = FALSE)

# restart R session ...

rsconnect::writeManifest()
#> ℹ Capturing R dependencies from renv.lock
#> ✔ Found 32 dependencies
#> Error in `createAppManifest()` at rstudio-rsconnect-8856765/R/writeManifest.R:61:2:
#> ! All packages must be installed from a reproducible location.
#> ✖ Can't re-install packages installed from source: shiny.
#> ℹ See `rsconnect::appDependencies()` for more details.
#> Run `rlang::last_trace()` to see where the error occurred.
```

### CODE REVIEW

**Comment by aronatkins** [comment]
I've pushed a second commit, which attempts to search for packages that have "Local" or "unknown" renv source.

```r
rsconnect::writeManifest()
#> ℹ Capturing R dependencies from renv.lock
#> ✔ Found 32 dependencies
jsonlite::fromJSON("manifest.json")$packages$shiny[c("Source","Repository")]
#> $Source
#> [1] "CRAN"
#> 
#> $Repository
#> [1] "https://packagemanager.posit.co/cran/latest"
```

@hadley - Which option do you feel we should use? Force folks to adjust their renv project to install from a repository, or search the repositories for those packages on their behalf?

**Comment by hadley** [comment]
I think this approach breaks the feature that I originally wanted — if you have a locally installed version of a CRAN (like we often do when developing packages) you'd get the CRAN package, which is likely what you wanted. I'm not sure how to balance that against the needs of this user.

**Comment by aronatkins** [comment]
@hadley - The first commit does what you want, then -- it errs on local packages. I'm happy to merge just that and discard the second commit (which searches).

@slodge-work - Could you confirm that you are comfortable installing your package from a repository rather than source?

**Comment by slodge-work** [comment]
@aronatkins There's a suggestion by @kevinushey to look at `options(renv.records.override = list(devtools = list(...)))` and that's given me other ideas of things to play with.

Thanks both for looking at this - it's really helped me understand what's happening here.

I do appreciate our build system and local CRAN are not completely following perfect R/CRAN workflows, and I confirm I'm comfortable to try our own local solutions/workarounds for the new challenge :+1:

**Comment by aronatkins** [comment]
@hadley - I've rolled back the search; this PR now treats "Local" as "unknown" and produces an error, which is the result you wanted, I think. See the original PR comment for the error message.

**Review by hadley — APPROVED** [review]

**Comment by toph-allen** [comment]
## Validation

Roughly following the instructions in the PR comment, except substituting the main branch for `renv::install("rstudio/rsconnect@aron-issue-1004", prompt = FALSE)`:

```
> renv::install("rstudio/rsconnect", prompt = FALSE)
# Downloading packages -------------------------------------------------------
- Downloading rsconnect from GitHub ...         OK [499.3 Kb in 0.69s]
Successfully downloaded 1 package in 0.83 seconds.

The following package(s) will be installed:
- rsconnect [rstudio/rsconnect@main]
These packages will be installed into "~/Local/RStudio/projects/2023-10-03-rsconnect-qa/mixed-content/renv/library/R-4.3/aarch64-apple-darwin20".

# Installing packages --------------------------------------------------------
- Installing rsconnect ...                      OK [built from source and cached in 2.7s]
Successfully installed 1 package in 2.7 seconds.

The following loaded package(s) have been updated:
- rsconnect
Restart your R session to use the new versions.


Restarting R session...

- Project '~/Local/RStudio/projects/2023-10-03-rsconnect-qa/mixed-content' loaded. [renv 1.0.1; sha: 5dc2fc9]
> rsconnect::writeManifest()
ℹ Capturing R dependencies from renv.lock
✔ Found 32 dependencies
Error in `createAppManifest()` at rstudio-rsconnect-bf42453/R/writeManifest.R:61:2:
! All packages must be installed from a reproducible location.
✖ Can't re-install packages installed from source: shiny.
ℹ See `rsconnect::appDependencies()` for more details.
Run `rlang::last_trace()` to see where the error occurred.
```

From the discussion (treating "Local" as "unknown" and emitting an error), it looks like this is the expected outcome, so… consider this validated.

**Pull request merged**
