### PR TITLE
Improve self-signed certificate documentation and usage

### PR DESCRIPTION
**Pull request by jmcphers**
This change fixes a number of problems with the self-signed certificate support noted in a test pass from @dethmasque and @trestletech. 

- Specifying a certificate file that doesn't exist now shows a shorter, clearer error.
- A warning is now raised when a certificate store that does not exist is specified in the `rsconnect.ca.bundle` option. 
- A syntax error in `addServerCertificate` has been corrected.
- It is no longer possible to add certificates to HTTP endpoints (only HTTPS ones). 
- Documentation now states more clearly that cert files are copied into the configuration (not referenced). 

It also adds a few basic certificate storage and retrieval tests.

### CODE REVIEW

**Comment by trestletech** [comment]
This looks like a great improvement; thanks, @jmcphers .

One outstanding question for me was just the overall flow of how to create a server with a custom cert. It looked like there were opportunities to add a `certificate=` argument in one place. Or I could use the designated function to add a certificate. When I was playing with this with Toni I didn't walk away with a clear vision of the lifecycle of this process. 

Not sure if it would be more helpful to 1.) have docs on `addServer` and `addServerCertificate` explaining the relationship between the two, or 2.) have a high-level guide (support article?) that shows you how to get through this process from end to end?

**Comment by jmcphers** [comment]
You should almost always use the `certificate` argument to `addServer`. `addServerCertificate` just exists in case you added or changed the server's cert and want to update it.

I think a high-level guide is best. We are hoping to add some affordances to the IDE when you're first getting connected, so most users won't ever have to scrutinize the rsconnect docs themselves.

https://github.com/rstudio/rstudio/issues/1604

**Comment by dethmasque** [comment]
Copypasta from https://github.com/rstudio/connect/issues/8535:

Documentation around `certificate` now specifies that the cert is copied into the server's config file.

Certificates now cannot be added to servers using HTTP when using `addServer`, `addConnectServer` and `addServerCertificate`:

```
> rsconnect::addServerCertificate(name="192.168.42.14")

Error in rsconnect::addServerCertificate(name = "192.168.42.14") : 
  Certificates may only be attached to servers that use the HTTPS protocol. Sepecify an HTTPS URL for the server, or omit the certificate.

> rsconnect::addConnectServer(url="http://192.168.42.14", certificate= "/Users/questionsleep/Git/connect/cert.pem")
Enter a nickname for this server (default '192.168.42.14'): toot

Error in addServer(ensureConnectServerUrl(url), name, certificate, quiet) : 
  Certificates may only be attached to servers that use the HTTPS protocol. Sepecify an HTTPS URL for the server, or omit the certificate.
```

Specifying a certificate that does not exist now results in an error when using `addServer`, `addConnectServer` and `addServerCertificate`:

```
> rsconnect::addConnectServer(url="https://my-domain.com:4343", name = "certdoesntexist", certificate = "/i/am/not/a/real/cert.pem")

Error in inferCertificateContents(certificate) : 
  The certificate file '/i/am/not/a/real/cert.pem' does not exist.

> rsconnect::addServer(url="https://my-domain.com:4343", name = "nocert", certificate = "/i/do/not/exist/cert.pem")

Error in inferCertificateContents(certificate) : 
  The certificate file '/i/do/not/exist/cert.pem' does not exist.

> rsconnect::addServerCertificate(name="centos7cert2", certificate = "/not/a/real/cert.pem")

Error in inferCertificateContents(certificate) : 
  The certificate file '/not/a/real/cert.pem' does not exist.
```

But unfortunately now it does not seem to care what you give it for a cert as long as the file exists:

```
> rsconnect::addServerCertificate(name="centos7baddomain2", certificate = "/Users/questionsleep/Git/connect/shiny-server-commercial-1.5.6.10-rh5-x86_64.rpm")

Certificate added to server 'centos7baddomain2'

> rsconnect::addConnectServer(url="https://my-domain.com:4343", certificate = "/Users/questionsleep/Downloads/4ItKM90tjD.gif")

Enter a nickname for this server (default 'my-domain.com'): centos7gifcert
Server 'centos7gifcert' added successfully: https://my-domain.com:4343/__api__
```

Attempting to `connectUser` on a server with a bogus cert causes the following error:

```
> rsconnect::connectUser("centos7gifcert")

Error in read.dcf(file) : 
  Found continuation line starting ' . ...' at begin of record.
```

I am also not getting an error when specifying a cert store that does not exist:

```
> options(rsconnect.ca.bundle = "/aoeifowefo/afejwoef")
>
> getOption("rsconnect.ca.bundle")
[1] "/aoeifowefo/afejwoef"
```

But when I `addConnectServer` then `connectUser` without specifying a cert it yells a whole lot about that cert store not existing:

```
> rsconnect::addConnectServer(url="https://my-domain.com:4343", name = "centos7nocertprovided")

Server 'centos7nocertprovided' added successfully: https://my-domain.com:4343/__api__

> rsconnect::connectUser(server="centos7nocertprovided")

A browser window should open; if it doesn't, you may authenticate manually by visiting https://my-domain.com:4343/connect/#/tokens/T1755ca1cb2df95e8d219237792a6598e/activate.
Waiting for authentication...
Account registered successfully: Toni Noble (toni)
Warning messages:
1: In createCertificateFile(authInfo$certificate) :
  The certificate store '/aoeifowefo/afejwoef' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
2: In createCertificateFile(authInfo$certificate) :
  The certificate store '/aoeifowefo/afejwoef' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
3: In createCertificateFile(authInfo$certificate) :
  The certificate store '/aoeifowefo/afejwoef' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
4: In createCertificateFile(authInfo$certificate) :
  The certificate store '/aoeifowefo/afejwoef' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
5: In createCertificateFile(authInfo$certificate) :
  The certificate store '/aoeifowefo/afejwoef' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
6: In createCertificateFile(authInfo$certificate) :
  The certificate store '/aoeifowefo/afejwoef' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
7: In createCertificateFile(authInfo$certificate) :
  The certificate store '/aoeifowefo/afejwoef' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
8: In createCertificateFile(authInfo$certificate) :
  The certificate store '/aoeifowefo/afejwoef' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
9: In createCertificateFile(authInfo$certificate) :
  The certificate store '/aoeifowefo/afejwoef' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
```

I added the server again using `addConnectServer` under a different name, attached the cert to it, then ran `connectUser` and that produced a few of the `rsconnect.ca.bundle` errors as well as some `dir.create` ones due to existing directories:

```
> rsconnect::addConnectServer(url="https://my-domain.com:4343", name = "centos7nocertprovided2")

Server 'centos7nocertprovided2' added successfully: https://my-domain.com:4343/__api__

> rsconnect::addServerCertificate(name = "centos7nocertprovided2", certificate = "/Users/questionsleep/Git/connect/cert.pem")

Certificate added to server 'centos7nocertprovided2'

> rsconnect::connectUser(server="centos7nocertprovided2")

A browser window should open; if it doesn't, you may authenticate manually by visiting https://my-domain.com:4343/connect/#/tokens/Ta930b1faacb26df12301883f6c31a4e2/activate.
Waiting for authentication...
Account registered successfully: Toni Noble (toni)
Warning messages:
1: In createCertificateFile(authInfo$certificate) :
  The certificate store '/aoeifowefo/afejwoef' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
2: In dir.create(dirname(certificateStore)) :
  '/var/folders/ck/zn71p6qj4qq6x32sbj57s5xr0000gn/T//RtmpkwhEnP' already exists
3: In createCertificateFile(authInfo$certificate) :
  The certificate store '/aoeifowefo/afejwoef' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
4: In dir.create(dirname(certificateStore)) :
  '/var/folders/ck/zn71p6qj4qq6x32sbj57s5xr0000gn/T//RtmpkwhEnP' already exists
5: In createCertificateFile(authInfo$certificate) :
  The certificate store '/aoeifowefo/afejwoef' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
6: In dir.create(dirname(certificateStore)) :
  '/var/folders/ck/zn71p6qj4qq6x32sbj57s5xr0000gn/T//RtmpkwhEnP' already exists
```

Deploying to either server produces similar results.

**Comment by jmcphers** [comment]
> But unfortunately now it does not seem to care what you give it for a cert as long as the file exists

It is a good idea to validate the cert file in some way! I have just pushed a change that does this.

> I am also not getting an error when specifying a cert store that does not exist:

Unfortunately we can't do anything about this; the `options` command is part of R, so we can't validate it at the time it's set, only when we try to use the option. 

 > it yells a whole lot about that cert store not existing:

Yes, you'll get a warning every time it tries to connect to the server, and when you call `connectUser` it polls the server lots of times so you get lots of warnings. It's ugly, but it's unlikely and I don't think it's worth trying to roll them up (let me know if you disagree!)

>  as well as some dir.create ones due to existing directories:

I have also pushed a change that fixes this.

> on a server with a bogus cert causes the following error:

It should no longer be possible to add bogus certs so hopefully this error is now unreachable!

**Comment by dethmasque** [comment]
Testing changes from https://github.com/rstudio/rsconnect/pull/252#issuecomment-369679772

`addServer, `addConnectServer`, and `addServerCertificate` now care what you provide for the cert: 

```
> rsconnect::addServer(url="https://my-domain.com:4343", name = "asdfasdf", certificate = "/Users/questionsleep/fff.Rmd")

Error in inferCertificateContents(certificate) : 
  The file '/Users/questionsleep/fff.Rmd' does not appear to be a certificate. Certificate files should be in ASCII armored PEM format, with a first line reading -----BEGIN CERTIFICATE-----.

> rsconnect::addConnectServer(url="https://my-domain:4343", name = "asdfasdfdfd", certificate = "/Users/questionsleep/plot cars.R")

Error in inferCertificateContents(certificate) : 
  The file '/Users/questionsleep/plot cars.R' does not appear to be a certificate. Certificate files should be in ASCII armored PEM format, with a first line reading -----BEGIN CERTIFICATE-----.

> rsconnect::addServerCertificate(name="centos7cert2", certificate = "/Users/questionsleep/Applications/.localized")

Error in inferCertificateContents(certificate) : 
  The file '/Users/questionsleep/Applications/.localized' does not appear to be a certificate. Certificate files should be in ASCII armored PEM format, with a first line reading -----BEGIN CERTIFICATE-----.
```

But when I provided larger non-cert files such as `.rpm` or `.dmg` I received this error:

```
> rsconnect::addServerCertificate(name="centos7cert2", certificate = "/Users/questionsleep/rstudio-connect-1.5.11-2316.x86_64.rpm")

Error: C stack usage  123856450 is too close to the limit

> rsconnect::addServerCertificate(name="centos7cert2", certificate = "/Users/questionsleep/Downloads/Docker.dmg")

Error: C stack usage  386099802 is too close to the limit
```

I was unable to reproduce the above issue using smaller-sized files. 

I'm also now getting errors when trying to `connectUser` on a newly added Connect server regardless of whether or not a certificate is specified when adding it:

```
> rsconnect::addConnectServer(url="https://my-domain.com:4343", name = "centos7cert3", certificate = "/Users/questionsleep/Git/connect/cert.pem")

Server 'centos7cert3' added successfully: https://my-domain.com:4343/__api__

> rsconnect::connectUser("centos7cert3")

Error in read.dcf(file) : 
  Found continuation line starting ' . ...' at begin of record.

> rsconnect::addConnectServer(url="https://my-domain.com:4343", name = "centos7cert4")

Server 'centos7cert4' added successfully: https://my-domain.com:4343/__api__

> rsconnect::connectUser("centos7cert4")

Error in read.dcf(file) : 
  Found continuation line starting ' . ...' at begin of record.
```

Attempting to deploy to severs with either HTTP or HTTPS provides the following error:

```
> rsconnect::deployApp(appDir= "/Users/questionsleep/shiny rmd.Rmd", server = "centos7cert2", account = "Robert.")

Loading required namespace: rmarkdown
Discovering document dependencies... OK
Error in inferCertificateContents(system.file("cert/shinyapps.io.pem",  : 
  The file '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rsconnect/cert/shinyapps.io.pem' does not appear to be a certificate. Certificate files should be in ASCII armored PEM format, with a first line reading -----BEGIN CERTIFICATE-----.

> rsconnect::deployApp(appDir= "/Users/questionsleep/shiny rmd.Rmd", server = "centos7cert2", account = "toni")

Discovering document dependencies... OK
Error in inferCertificateContents(system.file("cert/shinyapps.io.pem",  : 
  The file '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rsconnect/cert/shinyapps.io.pem' does not appear to be a certificate. Certificate files should be in ASCII armored PEM format, with a first line reading -----BEGIN CERTIFICATE-----.

> rsconnect::deployApp(appDir= "/Users/questionsleep/shiny rmd.Rmd", server = "centos7nocertprovided2", account = "toni")

Discovering document dependencies... OK
Error in inferCertificateContents(system.file("cert/shinyapps.io.pem",  : 
  The file '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rsconnect/cert/shinyapps.io.pem' does not appear to be a certificate. Certificate files should be in ASCII armored PEM format, with a first line reading -----BEGIN CERTIFICATE-----.

> rsconnect::deployApp(appDir= "/Users/questionsleep/shiny rmd.Rmd", server = "centos7http", account = "toni")

Discovering document dependencies... OK
Error in inferCertificateContents(system.file("cert/shinyapps.io.pem",  : 
  The file '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rsconnect/cert/shinyapps.io.pem' does not appear to be a certificate. Certificate files should be in ASCII armored PEM format, with a first line reading -----BEGIN CERTIFICATE-----.
```

I have never pointed `rsconnect` toward that `shinyapps.io.pem` so I'm not sure what that is about.

Cert errors are being provided when connecting a user to an HTTP server:

```
> rsconnect::addConnectServer(url="http://192.168.42.14:3939", name = "centos7http")

Server 'centos7http' added successfully: http://192.168.42.14:3939/__api__

> rsconnect::connectUser(server="centos7http")

A browser window should open; if it doesn't, you may authenticate manually by visiting http://192.168.42.14:3939/connect/#/tokens/Tbafd04a8130ea111d7b39189f18fdd4b/activate.
Waiting for authentication...
Account registered successfully: Toni Noble (toni)
Warning messages:
1: In createCertificateFile(authInfo$certificate) :
  The certificate store '/non/existent/dir/' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
2: In createCertificateFile(authInfo$certificate) :
  The certificate store '/non/existent/dir/' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
3: In createCertificateFile(authInfo$certificate) :
  The certificate store '/non/existent/dir/' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
4: In createCertificateFile(authInfo$certificate) :
  The certificate store '/non/existent/dir/' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
5: In createCertificateFile(authInfo$certificate) :
  The certificate store '/non/existent/dir/' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
6: In createCertificateFile(authInfo$certificate) :
  The certificate store '/non/existent/dir/' specified in the rsconnect.ca.bundle option does not exist. The system certificate store will be used instead.
```

**Comment by jmcphers** [comment]
> But when I provided larger non-cert files such as .rpm or .dmg I received this error:

This is because we try to read the whole file in to see if it's a certificate. Hopefully people will not try this very often in the wild! Just in case, I've added an error if you try to install a certificate file that exceeds 1Mb.

> Cert errors are being provided when connecting a user to an HTTP server:

There's no reason for us to supply certificates with HTTP, so I've turned this off.

> Attempting to deploy to severs with either HTTP or HTTPS provides the following error:

This should be fixed now -- the certificate validation was a little too touchy.

Finally, I was not able to reproduce this error:

   Error in read.dcf(file) : 
     Found continuation line starting ' . ...' at begin of record.

If you're still seeing it (after sync'ing to the latest and re-adding the server), could you post an issue w/ the contents of the .crt you're adding?

**Comment by dethmasque** [comment]
Deploying to servers using HTTP no longer produces cert errors.

Attempting to add a large file as a certificate to a server provides an error:

```
> rsconnect::addServerCertificate(name="centos7cert4", certificate = "/Users/questionsleep/Downloads/Docker.dmg")

Error in inferCertificateContents(certificate) : 
  The file '/Users/questionsleep/Downloads/Docker.dmg' is too large. Certificate files must be less than 1MB.

> rsconnect::addServer(url="https://my-domain.com:4343", name = "doot", certificate = "/Users/questionsleep/Downloads/Docker.dmg")

Error in inferCertificateContents(certificate) : 
  The file '/Users/questionsleep/Downloads/Docker.dmg' is too large. Certificate files must be less than 1MB.

> rsconnect::addConnectServer(url="https://my-domain.com:4343", name = "doot", certificate = "/Users/questionsleep/Downloads/Docker.dmg")

Error in inferCertificateContents(certificate) : 
  The file '/Users/questionsleep/Downloads/Docker.dmg' is too large. Certificate files must be less than 1MB.
```

I am still seeing that error, but it doesn't seem to care whether or not you're providing a cert as it occurs when trying to connect servers using HTTP:

```
> rsconnect::addConnectServer(url="http://192.168.42.31:3939/", name="centos6passhttp")

Server 'centos6passhttp' added successfully: http://192.168.42.31:3939/__api__

> rsconnect::connectUser("centos6passhttp")

Error in read.dcf(file) : 
  Found continuation line starting ' . ...' at begin of record.
```

```
Tonis-MacBook-Pro:servers questionsleep$ cat centos6passhttp.dcf
name: centos6passhttp
url: http://192.168.42.31:3939/__api__
```

**Comment by dethmasque** [comment]
I figured out what was happening there. When it was trying to connect the user `rsconnect` wanted to list all of the available server names, but it couldn't because of the messed up servers that had GIFs for certs and whatnot. After I deleted those `.dcf` files from the `servers` directory I was able to successfully connect:

```
> rsconnect::addConnectServer(url="http://192.168.42.31:3939/", name="centos6passhttp2")

Server 'centos6passhttp2' added successfully: http://192.168.42.31:3939/__api__

> rsconnect::connectUser("centos6passhttp2")

Registered servers: 127.0.0.1, 192.168.42.12, 192.168.42.14, 192.168.42.16, 192.168.42.17, 192.168.42.26, 192.168.42.27, 192.168.42.40, beta, beta.rstudioconnect.com, centos6passhttp, centos6passhttp2, centos6password, centos7baddomain, centos7cert, centos7cert2, centos7cert3, centos7cert4, centos7cert5, centos7cert6, centos7certed, centos7http, centos7http2, centos7nocertprovided, centos7nocertprovided2, rsc.radixu.com, ubuntu16_pam, ubuntu16-pam, Ubuntu16Pam, Ubuntu16PamCerted, Ubuntu16PamCerted2

Which server (default '127.0.0.1')? centos7http2

A browser window should open; if it doesn't, you may authenticate manually by visiting http://my-domain.com:3939/connect/#/tokens/Tb8d7c6858c9dacb8d3bba6795a71b47c/activate.
Waiting for authentication...
Account registered successfully: Toni Noble (toni)
```

I believe that means we are good to go to release to CRAN. :)

**Pull request merged**
